---
version: "3.6"
services:
  postgresql:
    image: postgres:11.3
    container_name: postgres
    volumes:
      - fitx-data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=fitx
    ports: ["5432:5432"]
    networks: ["stack"]
    healthcheck:
      test: curl -s https://localhost:5432 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  fitx-data:
networks:
  stack:
